#if 0
// Copyright (C) 2023-2026 University Corporation for Atmospheric Research
// SPDX-License-Identifier: Apache-2.0
#endif

#define MUSICA_STATUS_SUCCESS 0

#define MUSICA_SEVERITY_INFO     0
#define MUSICA_SEVERITY_WARNING  1
#define MUSICA_SEVERITY_ERROR    2
#define MUSICA_SEVERITY_CRITICAL 3

#define MUSICA_ERROR_CATEGORY                "MUSICA Error"
#define MUSICA_ERROR_CODE_UNKNOWN            1
#define MUSICA_ERROR_CODE_MAPPING_NOT_FOUND  2
#define MUSICA_ERROR_CODE_MAPPING_OPTIONS_UNDEFINED 3

#define MUSICA_MICM_ERROR_CATEGORY                        "MUSICA MICM Error"
#define MUSICA_MICM_ERROR_CODE_SPECIES_NOT_FOUND          1
#define MUSICA_MICM_ERROR_CODE_SOLVER_TYPE_NOT_FOUND      2
#define MUSICA_MICM_ERROR_CODE_UNSUPPORTED_SOLVER_STATE_PAIR 3

#define MUSICA_PARSE_ERROR_CATEGORY                       "MUSICA Parse Error"
#define MUSICA_PARSE_ERROR_CODE_PARSING_FAILED            1
#define MUSICA_PARSE_ERROR_CODE_INVALID_CONFIG_FILE       2
#define MUSICA_PARSE_ERROR_CODE_UNSUPPORTED_VERSION       3
#define MUSICA_PARSE_ERROR_CODE_FAILED_TO_CAST_TO_VERSION 4