FROM fedora:41

ARG BUILD_TYPE=Debug

RUN dnf -y update \
    && dnf -y install \
        cmake \
        curl \
        gcc-c++ \
        gdb \
        git \
        hdf5-devel \
        lapack-devel \
        libcurl-devel \
        m4 \
        make \
        netcdf-fortran-devel \
        valgrind \
        zlib-devel \
    && dnf clean all

COPY . musica

# TODO(miam): MIAM v0.1.0 does not support MICM v3.14.0. Re-enable once MIAM is ported.
RUN cd musica \
    && cmake -S . \
             -D MUSICA_ENABLE_MIAM=OFF \
             -B build \
             -D CMAKE_BUILD_TYPE=${BUILD_TYPE} \
             -D MUSICA_ENABLE_TESTS=ON \
             -D MUSICA_BUILD_FORTRAN_INTERFACE=ON \
             -D MUSICA_ENABLE_MEMCHECK=ON \
             -D MUSICA_ENABLE_CARMA=OFF \
    && cd build \
    && make install -j$(nproc)

WORKDIR /musica/build
