FROM fedora:latest

RUN dnf -y update \
    && dnf -y install \
        cmake \
        curl \
        gcc-c++ \
        gcc-gfortran \
        git \
        hdf5-devel \
        lapack-devel \
        libcurl-devel \
        m4 \
        make \
        netcdf-fortran-devel \
        pip \
        python \
        python-devel \
        zlib-devel \
    && dnf clean all

COPY . musica

ENV CXX=g++
ENV CC=gcc
ENV FC=gfortran

RUN cd musica && pip install -e .[test,tutorial]

WORKDIR /musica