FROM --platform=linux/amd64 python:3.12-slim

COPY wheelhouse/ wheelhouse/

RUN apt update && \
    apt install -y \
      binutils

RUN pip install --upgrade pip
RUN pip install "musica[gpu] @ file:/wheelhouse/musica-0.11.1.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl"

CMD ["bash"]
