FROM quay.io/pypa/manylinux2014_x86_64

RUN yum install -y patchelf unzip zip git

COPY . /musica

WORKDIR /musica

# Install Python build tools
RUN /opt/python/cp312-cp312/bin/pip install cibuildwheel

# Default command (override with docker run)
CMD ["env", "CIBW_PLATFORM=linux", "/opt/python/cp312-cp312/bin/python", "-m", "cibuildwheel", "--output-dir", "wheelhouse"]