FROM fedora:latest

RUN dnf -y update \
    && dnf -y install \
        cmake \
        gcc-c++ \
        gcc-fortran \
        gdb \
        git \
        lapack-devel \
        make \
        netcdf-fortran-devel \
        python3 \
        python3-devel \
        python3-pip \
        python3-setuptools \
    && dnf clean all

COPY . /musica/

ENV CXX=g++
ENV CC=gcc
ENV FC=gfortran

RUN cd /musica \
    && pip3 install --verbose .[test]

WORKDIR /musica
CMD ["pytest"]