FROM fedora:latest

RUN dnf -y update \
    && dnf -y install \
        cmake \
        gcc-c++ \
        gcc-fortran \
        gdb \
        git \
        make \
        netcdf-fortran-devel \
        python3 \
        python3-devel \
        python3-pip \
        python3-setuptools \
    && dnf clean all

COPY . /musica/

ENV CXX=g++
ENV CC=gcc
ENV FC=gfortran

RUN mkdir /build \
      && cd /build \
      && cmake \
        -D CMAKE_BUILD_TYPE=debug \
        -D MUSICA_ENABLE_PYTHON_LIBRARY=ON \
        /musica \
      && make install -j 8

RUN cd /build/_deps/mechanism_configuration-src \
    && python3 -m pip install --upgrade wheel setuptools pytest \
    && pip3 install --verbose .[test]

RUN cd /musica \
    && pip3 install --verbose .[test]

WORKDIR /musica
CMD ["python3", "-m", "unittest", "discover", "-v", "-s", "musica/test"]