# CMake generated Testfile for 
# Source directory: /home/runner/work/musica/musica/fortran/test/integration
# Build directory: /home/runner/work/musica/musica/build_test/fortran/test/integration
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[micm_fortran_api]=] "/home/runner/work/musica/musica/build_test/test_micm_fortran_api")
set_tests_properties([=[micm_fortran_api]=] PROPERTIES  TIMEOUT "20" WORKING_DIRECTORY "/home/runner/work/musica/musica/build_test" _BACKTRACE_TRIPLES "/home/runner/work/musica/musica/cmake/test_util.cmake;77;add_test;/home/runner/work/musica/musica/cmake/test_util.cmake;47;add_musica_test;/home/runner/work/musica/musica/fortran/test/integration/CMakeLists.txt;4;create_standard_test_fortran;/home/runner/work/musica/musica/fortran/test/integration/CMakeLists.txt;0;")
add_test([=[micm_box_model]=] "/home/runner/work/musica/musica/build_test/test_micm_box_model")
set_tests_properties([=[micm_box_model]=] PROPERTIES  TIMEOUT "20" WORKING_DIRECTORY "/home/runner/work/musica/musica/build_test" _BACKTRACE_TRIPLES "/home/runner/work/musica/musica/cmake/test_util.cmake;77;add_test;/home/runner/work/musica/musica/cmake/test_util.cmake;47;add_musica_test;/home/runner/work/musica/musica/fortran/test/integration/CMakeLists.txt;5;create_standard_test_fortran;/home/runner/work/musica/musica/fortran/test/integration/CMakeLists.txt;0;")
add_test([=[micm_multiple_grid_cells]=] "/home/runner/work/musica/musica/build_test/test_micm_multiple_grid_cells")
set_tests_properties([=[micm_multiple_grid_cells]=] PROPERTIES  TIMEOUT "20" WORKING_DIRECTORY "/home/runner/work/musica/musica/build_test" _BACKTRACE_TRIPLES "/home/runner/work/musica/musica/cmake/test_util.cmake;77;add_test;/home/runner/work/musica/musica/cmake/test_util.cmake;47;add_musica_test;/home/runner/work/musica/musica/fortran/test/integration/CMakeLists.txt;6;create_standard_test_fortran;/home/runner/work/musica/musica/fortran/test/integration/CMakeLists.txt;0;")
add_test([=[demo_fortran]=] "/home/runner/work/musica/musica/build_test/test_demo_fortran")
set_tests_properties([=[demo_fortran]=] PROPERTIES  TIMEOUT "20" WORKING_DIRECTORY "/home/runner/work/musica/musica/build_test" _BACKTRACE_TRIPLES "/home/runner/work/musica/musica/cmake/test_util.cmake;77;add_test;/home/runner/work/musica/musica/cmake/test_util.cmake;47;add_musica_test;/home/runner/work/musica/musica/fortran/test/integration/CMakeLists.txt;7;create_standard_test_fortran;/home/runner/work/musica/musica/fortran/test/integration/CMakeLists.txt;0;")
add_test([=[tutorial_multiple_mechanisms]=] "/home/runner/work/musica/musica/build_test/test_tutorial_multiple_mechanisms")
set_tests_properties([=[tutorial_multiple_mechanisms]=] PROPERTIES  TIMEOUT "20" WORKING_DIRECTORY "/home/runner/work/musica/musica/build_test" _BACKTRACE_TRIPLES "/home/runner/work/musica/musica/cmake/test_util.cmake;77;add_test;/home/runner/work/musica/musica/cmake/test_util.cmake;47;add_musica_test;/home/runner/work/musica/musica/fortran/test/integration/CMakeLists.txt;8;create_standard_test_fortran;/home/runner/work/musica/musica/fortran/test/integration/CMakeLists.txt;0;")
