name: EMSDK Setup
description: Setup EMSDK to build WebAssembly modules

inputs:
  em-version:
    description: 'emsdk version'
    default: '4.0.22'
  export-globally:
    description: 'If true, add EMSDK to PATH and ENV for remaining steps'
    default: 'false'

outputs:
  emsdk-env-file:
    description: "Path to a file containing EMSDK environment variables you can source"
    value: ${{ steps.activate_emsdk.outputs.emsdk-env-file }}

runs:
  using: "composite"
  steps:
    - name: Setup emscripten
      uses: mymindstorm/setup-emsdk@v14
      with:
        no-install: true
        version: ${{ inputs.em-version }}

    - name: Activate emscripten
      id: activate_emsdk
      shell: bash
      env:
        EM_VERSION: ${{ inputs.em-version }}
        EXPORT_GLOBALLY: ${{ inputs.export-globally }}
      run: |
        EMSDK_ENV_FILE=/tmp/emsdk.env

        # Install and activate EMSDK
        emsdk install ${EM_VERSION}
        emsdk activate ${EM_VERSION}

        # Construct env without putting EMSDK Node first
        EMSDK_QUIET=1 EMSDK_BASH=1 emsdk construct_env \
          | grep -v '^EMSDK_NODE=' \
          | grep '^export ' \
          | sed -e 's/^export //' -e 's/;$//' \
          > "${EMSDK_ENV_FILE}"

        # Optionally export globally for remaining steps (skip EMSDK_NODE)
        if [ "$EXPORT_GLOBALLY" = "true" ]; then
          grep '^PATH=' "${EMSDK_ENV_FILE}" | sed 's/^PATH=//' | tr -d '"' | while IFS=: read -ra p; do
            for d in "${p[@]}"; do
              echo "$d" >> "$GITHUB_PATH"
            done
          done
          grep -v '^PATH=' "${EMSDK_ENV_FILE}" >> "$GITHUB_ENV"
        fi

        # Set output for workflow
        echo "emsdk-env-file=${EMSDK_ENV_FILE}" >> "$GITHUB_OUTPUT"