name: musica-env
channels:
  - conda-forge
dependencies:
  - cmake
  - cxx-compiler
  - gfortran
  - ipycytoscape
  - ipykernel
  - libblas
  - liblapack
  - make
  - netcdf-fortran
  - pip
  - yaml-cpp
  - python=3.12
