#!/bin/bash
set -e

export PKG_CONFIG_PATH="${CONDA_PREFIX}/lib/pkgconfig:${CONDA_PREFIX}/share/pkgconfig:${PKG_CONFIG_PATH}"
export CMAKE_PREFIX_PATH="${CONDA_PREFIX}:${CMAKE_PREFIX_PATH}"

# Build from source
pip install .[tutorial]

# Install from the latest PyPI release
# pip install musica[tutorial]