name: Docker

on: 
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  docker-build-and-test:
    name: Build and Test - ${{ matrix.dockerfile }} - ${{ matrix.build_type }}
    env:
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        dockerfile:
          - Dockerfile
          - Dockerfile.memcheck
          - Dockerfile.fortran-gcc
          - Dockerfile.openmp
          - Dockerfile.mpi
          - Dockerfile.mpi_openmp
          - Dockerfile.nvhpc
          - Dockerfile.fortran-intel
          - Dockerfile.fortran-gcc.integration
          - Dockerfile.fortran-nvhpc
        build_type: [Release, Debug]
        exclude:
          - dockerfile: Dockerfile.nvhpc
            build_type: Debug

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Print branch name
        run: echo "Branch name is ${{ env.BRANCH_NAME }}"

      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false

      - uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/${{ matrix.dockerfile }}
          push: false
          tags: musica:${{ matrix.dockerfile }}-${{ matrix.build_type }}
          build-args: |
            MUSICA_GIT_TAG=${{ env.BRANCH_NAME }}
            BUILD_TYPE=${{ matrix.build_type }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run tests in container
        if: matrix.dockerfile != 'Dockerfile.nvhpc'
        run: docker run --rm -t musica:${{ matrix.dockerfile }}-${{ matrix.build_type }} \
              bash -c 'make test ARGS="--rerun-failed --output-on-failure -j8"'
